# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5a1a18ce9af823a909db5fab8df52191fa1d574c4e1f6ead772ca66e9f0108c8434ec3d92c705199fbf552372bbaef13739c23ede51625ab8eaa93da59381a44

test:
  secret_key_base: 85181b407a69d3da1e923338440ac2563a43f641f68bdb358782c58c309f30d74cfa144aa56d7306c29e9f8776fabc4b56ce6de8cf44f46945238a097deefa55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
